version: '3'
services:
  legacy-challenge-processor:
    image: legacy-challenge-processor:latest
    container_name: legacy-challenge-processor
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: run start
